---
title: "Data in project"
output: html_document
date: "2026-04-28"
---


#Data
```{r setup, include=FALSE}
excel_url <- "https://www.iceandclimate.nbi.ku.dk/data/GICC05modelext_GRIP_and_GISP2_and_resampled_data_series_Seierstad_et_al._2014_version_10Dec2014-2.xlsx"

res <- httr::GET(excel_url)
excel_file <- tempfile(fileext = ".xlsx")
writeBin(httr::content(res, as = "raw"), excel_file)

Ca2data <- readxl::read_excel(excel_file, sheet = 3,
                                range = "A51:I12278") %>%
  dplyr::slice(-1) %>%
  dplyr::select(1, ncol(.) - 1, ncol(.)) %>%
  dplyr::mutate_all(as.numeric) %>%
  dplyr::rename(age = 1, d18O = 2, Ca2 = 3)

unlink(excel_file)
data_file <- "Ca2data.csv"
readr::write_csv(Ca2data, data_file)
head(Ca2data)
```


#Preprocess the data
```{r}
library(zoo)
Ca2_final <- Ca2data %>%
  select(-d18O) %>%
  filter(age >= 30000, age <= 80000) %>%
  mutate(Ca2 = na.approx(Ca2)) %>%
  group_by(age) %>%
  summarise(Ca2 = mean(Ca2), .groups = "drop") %>%
  mutate(Ca2 = -log(Ca2)) %>%
  mutate(X = Ca2 - mean(Ca2)) %>%
  select(-Ca2) %>%
  mutate(age = age/1000) %>%
  mutate(V = (lead(X) - X)/0.02)
Ca2_final
```
#Plot af data
```{r}
ggplot(Ca2_final, aes(x = age, y = X)) +
  geom_line(color = "black") +
  scale_x_reverse() +
  labs(title = "Plot of Data",
       x = "Age (kyr BP)", 
       y = "X_t") +
  theme_minimal()
```


#Define the mean
```{r}
library(expm)
h <- 0.02
#theta=c(eta,a,b,c,d,alpha,beta,gamma)
theta <- c(1,2,3,4,5,6,7,8) #Data fra side 2 fra Predrags papir
A <- function(theta) {
  result <- matrix(data=c(0,theta[4],1,-theta[1]), nrow = 2,ncol = 2)
  return(result)
}
A(theta)
b <- function(theta) {
  result <- c(-theta[5]/theta[4],0) #Opmærksom på c\neq0
  return(result)
}
b(theta)
mu_h <- function(x, h, theta) {
  A_mat <- A(theta)
  b_vec <- b(theta)
  result <- expm(A_mat*h)%*%(x - b_vec) + b_vec
  return(result)
}
f <- function(x, h, theta) {
  result <- c(x[1],x[2]+h*(theta[2]*x[1]^3+theta[3]*x[1]^2))
  return(result)
}
mu_h(c(Ca2_final$X[1],Ca2_final$V[1]),h,theta)
```


#Now Omega
#First we find M1-M5
```{r}
#Kronecker product is sort of the same as tensor product
#M and I are defined on page 10 in Strang splitting estimator
M1 <- function(theta) {
  alpha_mat <- matrix(0,4,4)
  alpha_mat[4,4] <- theta[6]
  A_mat <- A(theta)
  A <- kronecker(A_mat,diag(2)) + kronecker(diag(2),A_mat) 
  M <- rbind(
    cbind(A + alpha_mat, alpha_mat),
    cbind(matrix(0,4,4), A)
  )
  return(M)
}

M2 <- function(theta) {
  alpha_mat <- matrix(0,4,4)
  alpha_mat[4,4] <- theta[6]
  A_mat <- A(theta)
  A <- kronecker(A_mat,diag(2)) + kronecker(diag(2),A_mat)
  M <- rbind(
    cbind(A + alpha_mat, alpha_mat),
    cbind(matrix(0,4,4), kronecker(diag(2),(diag(2) + A_mat)))
  )
  return(M)
}

M3 <- function(theta) {
  alpha_mat <- matrix(0,4,4)
  alpha_mat[4,4] <- theta[6]
  A_mat <- A(theta)
  A <- kronecker(A_mat,diag(2)) + kronecker(diag(2),A_mat)
  M <- rbind(
    cbind(A + alpha_mat, alpha_mat),
    cbind(matrix(0,4,4), kronecker((A_mat + diag(2)),diag(2)))
  )
  return(M)
}

M4 <- function(theta) {
  alpha_mat <- matrix(0,4,4)
  alpha_mat[4,4] <- theta[6]
  A_mat <- A(theta)
  beta_mat <- matrix(0,nrow = 4,ncol = 2)
  beta_mat[4,2] <- theta[7]
  A <- kronecker(A_mat,diag(2)) + kronecker(diag(2),A_mat)
  M <- rbind(
    cbind(A + alpha_mat, beta_mat),
    cbind(matrix(0,nrow = 2,ncol = 4), A_mat)
  )
  return(M)
}

M5 <- function(theta) {
  alpha_mat <- matrix(0,4,4)
  alpha_mat[4,4] <- theta[6]
  A_mat <- A(theta)
  A <- kronecker(A_mat,diag(2)) + kronecker(diag(2),A_mat)
  M <- rbind(
    cbind(A + alpha_mat, diag(4)),
    cbind(matrix(0,4,4), matrix(0,4,4))
  )
  return(M)
}
```

#Then we find I1-I5
```{r}
I1 <- function(theta,h) {
  M1_mat <- expm(M1(theta)*h)
  return(M1_mat[1:4,5:8])
}

I2 <- function(theta,h) {
  M2_mat <- expm(M2(theta)*h)
  return(M2_mat[1:4,5:8])
}

I3 <- function(theta,h) {
  M3_mat <- expm(M3(theta)*h)
  return(M3_mat[1:4,5:8])
}

I4 <- function(theta,h) {
  M4_mat <- expm(M4(theta)*h)
  return(M4_mat[1:4,5:6])
}

I5 <- function(theta,h) {
  M5_mat <- expm(M5(theta)*h)
  return(M5_mat[1:4,5:8])
}
I1(theta,h)
I1(c(67.9, -97.8, 8.4, 66.2, -9.1, 64.4, 228.0, 4371.0),h)
```



#Omega
```{r}
Omega <- function(x,theta,h) {
  B <- b(theta)
  
  result <- I1(theta,h) %*% as.vector( (x-B) %*% t(x-B) ) + 
    I2(theta,h) %*% as.vector( (x-B) %*% t(B) ) +
    I3(theta,h) %*% as.vector( B %*% t(x-B) ) +
    I4(theta,h) %*% (x-B) +
    I5(theta,h) %*% c(0,0,0,theta[8])
  result <- matrix(result, nrow = sqrt(length(result))) # Unvectorize
  return(result)
}
Omega(c(2,2), c(67.9, -97.8, 8.4, 66.2, -9.1, 64.4, 228.0, 4371.0),h)
```

#loglikelihood
```{r}
#S is data
loglik <- function(theta, h, S) {
  eta <- theta[1]
  a <- theta[2]
  alpha <- theta[6]
  beta <- theta[7]
  gamma <- theta[8]
  
  if (eta < 0 || a >= 0 || alpha <= 0 || alpha >= 2 * eta || beta^2 >= 4 * alpha * gamma) {
    return(1e100)
  }
  
  nll <- 0 #Negative loglikelihood
  
  
  #Now we test what is wrong
  #Z <- vector("list",(length(S[,1])-3)) #Vector
  #f_inv <- vector("list",(length(S[,1])-3)) #Vector
  #mu <- vector("list",(length(S[,1])-3)) #Vector
  #omega <- vector("list",(length(S[,1])-3)) #Matrix
  #omega34 <- vector("list", (length(S[,1])-3)) #Matrix
  
  Z_tk = matrix(0, length(S[,1]), 2)
  
  for (i in 2:(length(S[,1])-2)){
    prev_data <- S[i-1,]
    curr_data <- S[i,]
    
    Z_tk[i,] <- f(curr_data, -h/2, theta) - mu_h(f(prev_data, h/2, theta), h, theta)
    omega_h <- Omega(f(prev_data, h/2, theta), theta, h)
    
    omega_34h <- Omega(f(prev_data, h/2, theta), theta, (3*h)/4) # To fix the way I have generated V, page 10 on "Strang splitting for parametric inference in second order stochast..."
    
    #omega_23h <- Omega(f(prev_data, h/2, theta), theta, (3*h)/2) # To fix the way I have generated V, page 10 on "Strang splitting for parametric inference in second order stochast..."

    
    logdet_omega_34h <- log(det(omega_34h)) # Eliminate bias

    
    nll <- nll + (4/3) * logdet_omega_34h + t(Z_tk[i,])%*%solve(omega_h)%*%Z_tk[i,]
    
    #nll <- nll + (2/3) * omega_23h[2,2] + (Z_tk[i,2]^2)/omega_h[2,2]

    
    #Z[i-1] <- Z_tk
    #f_inv[i-1] <- f(curr_data, -h/2, theta)
    #mu[i-1] <- mu_h(f(prev_data, h/2, theta), h, theta)
    #omega[i-1] <- omega_h
    #omega34[i-1] <- omega_34h
    
    
  }
  print(nll)
  return(nll)
  #my_list <- list("nll" = nll, "Z" = Z, "f_inv" = f_inv, "mu" = mu, "omega" = omega, "omega34" = omega34)
}
theta_test

loglik(theta_test, h, cbind(Ca2_final$X, Ca2_final$V))
#plot(Z[,1], type = "l")
#nll$nll
#nll$Z
#nll$f_inv
#nll$mu
#nll$omega
#nll$omega34
```













```{r}
matrix(0, length(S[,1]), 2)
      
```



```{r}
I1(theta_init,h)
```



#test
```{r}

theta_init <- c(50, -200, 10, 100, 10, 30, -5, 1000)
S <- cbind(Ca2_final$X, Ca2_final$V)
h <- 0.02

result_lbfgsb <- optim(
  par = theta_init,
  fn = loglik,
  S = S,
  h = h,
  method = "L-BFGS-B",
  control = list(
    factr = 1e2,
    maxit = 5000,
    trace = 1
  )
)

result_lbfgsb
print(result_lbfgsb)
```
























#test with one dimension
```{r}

theta_init <- c(50, -200, 10, 100, 10, 30, -5, 1000)
S <- cbind(Ca2_final$X, Ca2_final$V)
h <- 0.02

result_lbfgsb <- optim(
  par = theta_init,
  fn = loglik,
  S = S,
  h = h,
  method = "L-BFGS-B",
  control = list(
    factr = 1e8
  )
)

result_lbfgsb
print(result_lbfgsb)
```






